name = "article-ocr-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'ocr-pic'

[build]
command = "npm install && npm run build"